language: go
go:
  - 1.11.1
sudo: required
services:
  - docker

install: true

script:
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push catac/k8s_isi_provisioner;
    fi
